#!/bin/sh
set -eu

usage() {
	echo "usage: $0 --version VERSION --input DIRECTORY --output DIRECTORY" >&2
	exit 2
}

version=
input=
output=

while [ "$#" -gt 0 ]; do
	case "$1" in
		--version)
			[ "$#" -ge 2 ] || usage
			version=$2
			shift 2
			;;
		--input)
			[ "$#" -ge 2 ] || usage
			input=$2
			shift 2
			;;
		--output)
			[ "$#" -ge 2 ] || usage
			output=$2
			shift 2
			;;
		*) usage ;;
	esac
done

[ -n "$version" ] && [ -n "$input" ] && [ -n "$output" ] || usage

case "$version" in
	v*.*.*) ;;
	*)
		echo "version must use the vX.Y.Z form" >&2
		exit 2
		;;
esac

plain_version=${version#v}
workspace=$(mktemp -d "${TMPDIR:-/tmp}/grat-bottles.XXXXXX")
trap 'rm -rf "$workspace"' EXIT HUP INT TERM
mkdir -p "$output"

write_formula() {
	formula=$1
	printf '%s\n' \
		'class Grat < Formula' \
		'  desc "Run approved local development tasks safely"' \
		'  homepage "https://github.com/phranck/grat"' \
		"  url \"https://github.com/phranck/grat/archive/refs/tags/${version}.tar.gz\"" \
		"  version \"${plain_version}\"" \
		'  license "MIT"' \
		'' \
		'  depends_on "go" => :build' \
		'' \
		'  def install' \
		'    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/phranck/grat/internal/version.buildVersion=v#{version}"), "./cmd/grat"' \
		'    # The manual is generated by the binary that was just built, so it can' \
		'    # only ever describe that binary.' \
		'    (buildpath/"grat.1").write Utils.safe_popen_read(bin/"grat", "manual")' \
		'    man1.install "grat.1"' \
		'  end' \
		'' \
		'  test do' \
		'    assert_match "v#{version}", shell_output("#{bin}/grat version")' \
		'  end' \
		'end' >"$formula"
}

# The manual page says nothing about the platform it was produced on, so it is
# generated once, from the binary this runner can execute, and copied into every
# bottle. Producing it per platform would need a machine of that platform for no
# difference in the result.
manual="$workspace/grat.1"

# host_asset names the release asset this machine can execute, so the script
# works on a runner of any of the four targets and on a developer machine.
host_asset() {
	case "$(uname -s)" in
		Darwin) host_os=darwin ;;
		Linux) host_os=linux ;;
		*)
			echo "unsupported host system: $(uname -s)" >&2
			exit 1
			;;
	esac
	case "$(uname -m)" in
		x86_64 | amd64) host_arch=amd64 ;;
		arm64 | aarch64) host_arch=arm64 ;;
		*)
			echo "unsupported host architecture: $(uname -m)" >&2
			exit 1
			;;
	esac
	echo "$input/grat_${version}_${host_os}_${host_arch}"
}

write_manual() {
	native=$(host_asset)
	if [ ! -f "$native" ]; then
		echo "missing release asset needed for the manual page: $native" >&2
		exit 1
	fi
	chmod +x "$native"
	"$native" manual >"$manual"
	if [ ! -s "$manual" ]; then
		echo "the manual page came out empty" >&2
		exit 1
	fi
}

package() {
	target=$1
	tag=$2
	asset="$input/grat_${version}_${target}"
	archive="$output/grat-${plain_version}.${tag}.bottle.tar.gz"
	stage="$workspace/$tag/grat/$plain_version"

	if [ ! -f "$asset" ]; then
		echo "missing release asset: $asset" >&2
		exit 1
	fi

	mkdir -p "$stage/bin" "$stage/.brew" "$stage/share/man/man1"
	cp "$asset" "$stage/bin/grat"
	chmod 755 "$stage/bin/grat"
	cp "$manual" "$stage/share/man/man1/grat.1"
	write_formula "$stage/.brew/grat.rb"
	tar -C "$workspace/$tag" -czf "$archive" grat
}

write_manual

package darwin_amd64 tahoe
package darwin_arm64 arm64_tahoe
package linux_amd64 x86_64_linux
package linux_arm64 arm64_linux

echo "Homebrew bottles written to $output"
